version: "3.1"
services:
    www:
        build: .
        ports: 
            - ${WWW_PORT}:80
        volumes:
            - ./www:/var/www/html/
            - ./conf/conf.d:/usr/local/etc/php/conf.d/
            - ./conf/sites-enabled:/etc/apache2/sites-enabled
        links:
            - db:db
        networks:
            - default
    db: # This service *must* be called 'db'
        image: mariadb:latest
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
        volumes:
              #- ./dump:/docker-entrypoint-initdb.d
              #- ./conf/mysqlConf:/etc/mysql/conf.d
            - ./db:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - ${PMA_PORT}:80
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
volumes:
    persistent:
