<div class="content">
    <div class="wrapper" data-post-id="<?=$_GET['id'];?> ">

        <!-- 
        <div class="commentsCon">

            <div class="comment">
                <div class="commentHead">
                    <a class="commentHeadText" href="#">Felix</a>
                    <div class="commentTimePosted">3h</div>
                </div>
                <div class="commentBody">
                    <p class="commentText">Det var et mega fedt post</p>
                </div>
                <div class="commentFoot">
                    <div class="commentVotes">
                        <div class="commentUpvote">▲</div>
                        <div class="commentTotalVotes">5k</div>
                        <div class="commentDownvote">▼</div>
                    </div>
                </div>
            </div>

            <div class="comment">
                <div class="commentHead">
                    <a class="commentHeadText" href="#">Felix</a>
                    <div class="commentTimePosted">3h</div>
                </div>
                <div class="commentBody">
                    <p class="commentText">Det var et mega fedt post</p>
                </div>
                <div class="commentFoot">
                    <div class="commentVotes">
                        <div class="commentUpvote">▲</div>
                        <div class="commentTotalVotes">5k</div>
                        <div class="commentDownvote">▼</div>
                    </div>
                </div>
            </div>
        </div> -->
    </div>
</div>